---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 李俊豪.
--- DateTime: 2022/12/29 17:31
---0


-- 1.参数列表
--1.1 优惠卷ID
local voucherId = ARGV[1]
--1.2 用户ID
local userId = ARGV[2]
--1.3 订单id
local orderId = ARGV[3]

-- 2. 数据key
--2.1 库存key
local stockKey = 'seckill:stock:' .. voucherId
--2.2 订单key
local orderKey = 'seckill:order:' .. voucherId

--3.脚本业务
--3.1 判断库存是否充足 get stockKey
if(tonumber(redis.call('get', stockKey)) <=0 ) then
    --库存不足，返回1
    return 1;
end

--3.2 判断用户是否下单
if(redis.call('sismember', orderKey, userId) == 1) then
    --存在 说明重复下单

    return 2;
end

--3.3 减扣库存
redis.call('incrby', stockKey, -1)

--3.4 生成订单
redis.call('sadd', orderKey, userId)

--3.5 发送消息到队列中, XADD stream.orders * k1 v1 k2 v2 ...
--redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)



--成功返回 0
return 0;
